// Code generated by go-swagger; DO NOT EDIT.

// Package restapi example server
//
//  demonstrate otel middleware
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.17.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
