info:
  description: demonstrate otel middleware
  title: example server
  version: 0.17.0
swagger: "2.0"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/{userId}:
    get:
      parameters:
        - name: userId
          in: path
          type: integer
          format: int64
          required: true
      responses:
        "200":
          description: user info
          schema:
            $ref: "#/definitions/user"
        "404":
          description: user not found
definitions:
    user:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
          minLength: 1  

